### DISCUSSION TITLE
Grafana error: Cannot read properties of undefined (reading '0')

### DISCUSSION THREAD

**Discussion by taitruong** [informalsystems/hermes#3105] [Q&A]
Hi I have:
- setup Grafana as stated here: https://hermes.informal.systems/tutorials/production/setup-grafana.html
- started hermes locally (had to disable REST endpoint, since port 3000 is used by Grafana)

Now Grafana shows hermes log, but everything else (wallat balances, current numbers of workers, ...) is not showing ("No data"). Instead in console I see this error:
```sh
react_devtools_backend.js:2655 TypeError: Cannot read properties of undefined (reading '0')
    at BarChartPanel.tsx:102:21
    at Object.useMemo (react-dom.production.min.js:172:115)
```

It seems like it is not possible to collect the metrics - though I have enabled metrics in config.toml on port 3001.

What I also see in prometheus.yml is this scrape config: https://hermes.informal.systems/assets/prometheus.yaml

```yaml
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "hermes"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["host.docker.internal:3001"]
```

I wonder what `host.docker.internal:3001` is? Should this point to metrics URL (`localhost:3001`)?
