### DISCUSSION TITLE
Should I run 2 relayers to make bidirectional ICS-20  packet transfer work?

### DISCUSSION THREAD

**Discussion by dzmitry-lahoda** [informalsystems/hermes#3632] [Q&A]
I see that can send ICS-20 from A to B well. 
Also I see that sending from B to A, moves funds to  escrow, but packet never relayed.

Should I run 2 relayers for bidirectional channel transfer?

Now I run only one.

**Comment by faust403** [comment]
Actually you need only 1 relayer, but with 2 chains in it's config
For example relayer between pion-1 and osmo-test-5 would look like

```toml
[[chains]]
id = 'pion-1'
rpc_addr = 'rpc_node'
grpc_addr = 'grpc_node'
event_source = { mode = 'pull', url = 'websocket_node', batch_delay = '1s', max_retries = 4 }
rpc_timeout = '40s'
account_prefix = 'neutron'
key_name = 'main'
store_prefix = 'ibc'
default_gas = 5000000
max_gas = 50000000
gas_price = { price = 0.02, denom = 'untrn' }
gas_multiplier = 1.6
dynamic_gas_price = { enabled = true, multiplier = 1.2, max = 0.06 }
max_msg_num = 20
max_tx_size = 2097152
clock_drift = '20s'
max_block_time = '30s'
trusting_period = '5days'
ccv_consumer_chain = true
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
memo_prefix = 'Relayed by dzmitry-lahoda'

[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', '*']
]

[[chains]]
id = 'osmo-test-5'
rpc_addr = "rpc_node"
grpc_addr = "grpc_node"
event_source = { mode = 'push', url = 'websocket_node', batch_delay = '200ms' }
rpc_timeout = '10s'
account_prefix = 'osmo'
key_name = 'main'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 3000000
gas_price = { price = 0.025, denom = 'uosmo' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '3days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
memo_prefix = 'Relayed by dzmitry-lahoda'

[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-3937']
]
```

Where it'll relay everything from pion and only channel-3937 from osmosis testnet
