### ISSUE TITLE
Use dashes instead of underscores in TOML config

### ISSUE THREAD

**Issue by romac** [informalsystems/hermes#2242]
## Summary

Using dashes to separate words in the TOML config looks more readable to me, which no semantic change.

It is also the preferred convention for the Tendermint `config.toml` and the Cosmos SDK `app.toml`.

Example config using dashes:

```toml
# The global section has parameters that apply globally to the relayer operation.
[global]
log-level = 'info'

[mode]

[mode.packets]
enabled = true
clear-interval = 100
clear-on-start = true
tx-confirmation = true

[rest]
enabled = true
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'ibc-1'
type = 'CosmosSdk'
rpc-addr = 'http://127.0.0.1:26557'
grpc-addr = 'http://127.0.0.1:9091'
websocket-addr = 'ws://127.0.0.1:26557/websocket'
rpc-timeout = '10s'
account-prefix = 'cosmos'
key-name = 'testkey'
store-prefix = 'ibc'
default-gas = 100000
max-gas = 400000
gas-price = { price = 0.001, denom = 'stake' }
gas-adjustment = 0.1
max-msg-num = 30
max-tx-size = 2097152
clock-drift = '5s'
max-block-time = '30s'
trusting-period = '14days'
trust-threshold = { numerator = '1', denominator = '3' }
address-type = { derivation = 'cosmos' }
```

### Acceptance criteria

- [ ] Update the default `config.toml` to use dashes
- [ ] Update the _Configuration_ page in the guide to use dashes

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
