### ISSUE TITLE
prometheus.yaml/yml typo

### ISSUE THREAD

**Issue by taitruong** [informalsystems/hermes#3106]
In the install guide (https://hermes.informal.systems/tutorials/production/setup-grafana.html) it referes to these 3 files:
1. https://hermes.informal.systems/assets/docker-compose.yaml
2. https://hermes.informal.systems/assets/prometheus.yaml
3. https://hermes.informal.systems/assets/grafana_template.json

In docker-compose.yaml file it maps a local file prometheus.yml file:

```yaml
  prometheus:
    image: prom/prometheus:v2.38.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      - prometheus
```
So prometheus.yaml should better be renamed to prometheus.yml in `assets` folder.
