### ISSUE TITLE
[feature] add directory for individual chain configs

### ISSUE THREAD

**Issue by dylanschultzie** [informalsystems/hermes#3134]
## Summary

Right now the biggest hurdle to being an effective relayer is correctly setting up a network's gas price/max gas/etc. Currently a base config is provided for an initial [example](https://github.com/informalsystems/hermes/blob/1fec32e17226f75dcf815fbb01220a862b5b3b5a/config.toml), but having a place for each chain would be even more helpful. `rly` uses the chain-registry to store its "best practice" configs for each channel.

## Problem Definition

This will help get new relayers started by having a clear location to see "basic" chain configs.

## Acceptance Criteria

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dylanschultzie** [comment]
This would not include the top level config parameters, but the config for each individual chain itself. As an example, for evmos/evmos_9001-2:

```toml
[[chains]]
id = 'evmos_9001-2'

{% include 'ports.toml.j2' %}

rpc_timeout = '20s'
account_prefix = 'evmos'
key_name = 'relayer'
store_prefix = 'ibc'
address_type = { derivation = 'ethermint', proto_type = { pk_type = '/ethermint.crypto.v1.ethsecp256k1.PubKey' } }
default_gas = 400000
max_gas = 4000000
gas_price = { price = 20000000000, denom = 'aevmos' }
gas_multiplier = 1.2
max_msg_num = 15
max_tx_size = 2097152
clock_drift = '15s'
max_block_time = '10s'
trusting_period = '7days'
memo_prefix = '{{ memo }}'
trust_threshold = { numerator = '1', denominator = '3'}

[chains.packet_filter]
policy = 'allow'
list = [ ]
```

Note that I'm not making the claim that these are *perfect* settings, but they're better than what is currently provided by either the chain itself or hermes/informal - which is to say, not much.
