### ISSUE TITLE
REST API not working?

### ISSUE THREAD

**Issue by taitruong** [informalsystems/hermes#3591]
version: 1.6.0

Hi, trying to access `http://127.0.0.1:3000/version` (as stated in [docs](https://github.com/informalsystems/hermes/blob/master/guide/src/documentation/rest-api.md), but nothing happens. I remember it was working before :).

Metrics forks fine on port 3001: `http://127.0.0.1:3001/metrics`

My config:
```toml
[rest]
enabled = true
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001
```
