### ISSUE TITLE
grafana_template.json out of date?

### ISSUE THREAD

**Issue by taitruong** [informalsystems/hermes#3592]
I followed setup instructions [here](https://hermes.informal.systems/tutorials/production/setup-grafana.html).

Logs are showing up in dashboard, but infos in tiles like `Wallet balances` are all empty:
![image](https://github.com/informalsystems/hermes/assets/776986/d494e510-09b0-4535-a538-7275fc531946)

Looking `grafana_template.json` file for balances there is this:

```yaml
    {
      "datasource": {
        "type": "prometheus",
        "uid": "${DS_PROMETHEUS}"
      },
      "description": "Indicates if you have enough funds on your wallet. Hermes can not relay without spending gas. Thus, it is important to set alarms which monitor the gas.",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "fillOpacity": 80,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineWidth": 1,
            "scaleDistribution": {
              "type": "linear"
            }
          },
          "decimals": 0,
          "mappings": [],
          "min": -1,
          "thresholds": {
            "mode": "percentage",
            "steps": [
              {
                "color": "green",
                "value": null
              }
            ]
          },
          "unit": "short"
        },
        "overrides": [
          {
            "matcher": {
              "id": "byType",
              "options": "time"
            },
            "properties": [
              {
                "id": "custom.axisPlacement",
                "value": "hidden"
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 7,
        "w": 8,
        "x": 0,
        "y": 17
      },
      "id": 1,
      "options": {
        "barRadius": 0,
        "barWidth": 0.97,
        "groupWidth": 0.7,
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom"
        },
        "orientation": "horizontal",
        "showValue": "auto",
        "stacking": "none",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "xTickLabelRotation": 0,
        "xTickLabelSpacing": 100
      },
      "pluginVersion": "9.0.6",
      "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${DS_PROMETHEUS}"
          },
          "editorMode": "code",
          "exemplar": false,
          "expr": "wallet_balance{job=\"hermes\"}",
          "hide": false,
          "instant": true,
          "legendFormat": "{{chain}}: {{account}} ({{instance}})",
          "range": false,
          "refId": "A"
        }
      ],
      "title": "Wallet balances",
      "transformations": [],
      "transparent": true,
      "type": "barchart"
    },
```

Above there is this entry: `"expr": "wallet_balance{job=\"hermes\"}",`

But in log I have this:
> 2023-09-07T12:53:02.187618Z TRACE ThreadId(43) spawn:chain{chain=elgafar-1}:wallet{chain=elgafar-1}: wallet balance amount=39942099367 denom=ustars account=stars1zyvut4uve45fx2hc3gnya7thtyawdnwyzj9ygm
> 2023-09-07T12:53:03.201586Z TRACE ThreadId(46) spawn:chain{chain=uni-6}:wallet{chain=uni-6}: wallet balance amount=2381263031 denom=ujunox account=juno1zyvut4uve45fx2hc3gnya7thtyawdnwyqu3zyk
> 2023-09-07T12:53:05.398422Z TRACE ThreadId(50) spawn:chain{chain=pisco-1}:wallet{chain=pisco-1}: wallet balance amount=87353232 denom=uluna account=terra1zyvut4uve45fx2hc3gnya7thtyawdnwys2gep2
> 2023-09-07T12:53:05.842014Z TRACE ThreadId(51) event_source.websocket{chain=elgafar-1}: received an RPC event: tm.event = 'NewBlock' chain=elgafar-1
> 2023-09-07T12:53:06.260129Z TRACE ThreadId(52) event_source.websocket{chain=pisco-1}: received an RPC event: tm.event = 'NewBlock' chain=pisco-1
2023-09-07T12:53:06.343358Z TRACE ThreadId(51) event_source.websocket{chain=elgafar-1}: assembled batch chain=elgafar-1 len=1

I'm neither familiar with Grafana nor Prometheus, but this it scrape data from log file?

**Comment by taitruong** [comment]
Ok, guess it gets data from `http://localhost:3001/metrics`:
> # HELP wallet_balance The balance of each wallet Hermes uses per chain. Please note that when converting the balance to f64 a loss in precision might be introduced in the displayed value
> # TYPE wallet_balance gauge
> wallet_balance{account="juno1zyvut4uve45fx2hc3gnya7thtyawdnwyqu3zyk",chain="uni-6",denom="ujunox",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 2381263031
> wallet_balance{account="stars1zyvut4uve45fx2hc3gnya7thtyawdnwyzj9ygm",chain="elgafar-1",denom="ustars",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 39942099367
> wallet_balance{account="terra1zyvut4uve45fx2hc3gnya7thtyawdnwys2gep2",chain="pisco-1",denom="uluna",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 87353232

Still wondering why data is not shown. Also for testing I'm running Hermes locally, so I changed in `prometheus.yml` from `host.docker.internal:3001` to `localhost:3001`.

```yaml
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "hermes"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["host.docker.internal:3001"]
```

**Comment by taitruong** [comment]
Ok, `host.docker.internal:3001` is correct, I tried changing it to `host.docker.internal:3001/metrics` and then I get an error when adding Prometheus data source (`lookup Prometheus: no such host`).

**Comment by taitruong** [comment]
Looking into `http://localhost:3001/metrics`, there is:

```
# HELP messages_submitted_total Number of messages submitted to a specific chain
# TYPE messages_submitted_total counter
messages_submitted_total{chain="elgafar-1",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
# HELP otel_scope_info Instrumentation Scope metadata
# TYPE otel_scope_info gauge
otel_scope_info{otel_scope_name="hermes",otel_scope_version=""} 1
# HELP queries_cache_hits_total Number of cache hits for queries submitted by Hermes
# TYPE queries_cache_hits_total counter
queries_cache_hits_total{chain="elgafar-1",query_type="query_channel",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_cache_hits_total{chain="elgafar-1",query_type="query_client_state",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_cache_hits_total{chain="elgafar-1",query_type="query_connection",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_cache_hits_total{chain="elgafar-1",query_type="query_latest_height",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_cache_hits_total{chain="pisco-1",query_type="query_client_state",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 7
queries_cache_hits_total{chain="uni-6",query_type="query_client_state",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 28
# HELP queries_total Number of queries submitted by Hermes
# TYPE queries_total counter
queries_total{chain="elgafar-1",query_type="query_application_status",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="query_block",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="query_blocks",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="query_channel",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="query_channel_client_state",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="query_channels",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="query_client_connections",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 290
queries_total{chain="elgafar-1",query_type="query_client_state",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="query_clients",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 1
queries_total{chain="elgafar-1",query_type="query_commitment_prefix",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="query_config_params",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 1
queries_total{chain="elgafar-1",query_type="query_connection",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 288
queries_total{chain="elgafar-1",query_type="query_connection_channels",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 254
queries_total{chain="elgafar-1",query_type="query_connections",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="query_consensus_state",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="query_consensus_states",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="query_latest_height",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 1
queries_total{chain="elgafar-1",query_type="query_next_sequence_receive",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="query_packet_acknowledgements",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="query_packet_commitments",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="query_packet_events",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="query_staking_params",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 2
queries_total{chain="elgafar-1",query_type="query_txs",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="query_unreceived_acknowledgements",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="query_unreceived_packets",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="query_upgraded_consensus_state",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
queries_total{chain="elgafar-1",query_type="status",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 1
queries_total{chain="pisco-1",query_type="query_client_state",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 21
queries_total{chain="pisco-1",query_type="query_config_params",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 1
queries_total{chain="pisco-1",query_type="query_connection",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 27
queries_total{chain="pisco-1",query_type="query_latest_height",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 1
queries_total{chain="pisco-1",query_type="query_staking_params",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 2
queries_total{chain="pisco-1",query_type="status",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 1
queries_total{chain="uni-6",query_type="query_client_state",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 232
queries_total{chain="uni-6",query_type="query_config_params",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 1
queries_total{chain="uni-6",query_type="query_connection",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 228
queries_total{chain="uni-6",query_type="query_latest_height",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 1
queries_total{chain="uni-6",query_type="query_staking_params",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 2
queries_total{chain="uni-6",query_type="status",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 1
# HELP ws_events_total How many IBC events did Hermes receive via the websocket subscription
# TYPE ws_events_total counter
ws_events_total{chain="elgafar-1",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
# HELP ws_reconnect_total Number of times Hermes reconnected to the websocket endpoint
# TYPE ws_reconnect_total counter
ws_reconnect_total{chain="elgafar-1",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 0
```

Are these I can query for? Like this:
> queries_cache_hits_total{chain="uni-6",query_type="query_client_state",service_name="unknown_service",otel_scope_name="hermes",otel_scope_version=""} 28

So in Dashboard I tried this: `queries_cache_hits_total {job="hermes"}`

But still I get no data:
![image](https://github.com/informalsystems/hermes/assets/776986/d8ece91f-f508-4f88-ab17-ab31d9d7c71a)

**Comment by romac** [comment]
If you are not running Prometheus in a Docker container then yes you need to set `localhost:3001` as your target. You should also double check that the Prometheus data source in Grafana is configured correctly and points to `localhost`.

**Comment by taitruong** [comment]
> If you are not running Prometheus in a Docker container then yes you need to set `localhost:3001` as your target. You should also double check that the Prometheus data source in Grafana is configured correctly and points to `localhost`.

Everything's inside eycept Hermes running on localhost. I can see the logs scraped by Loki (also in docker). But prometheus doesnt seem to get data even data source tells me it is connected.

**Comment by romac** [comment]
Ok then yeah Prometheus should point to `host.docker.internal` and Grafana should use the Docker container name. Here in my case it's just `prometheus`:

<img width="592" alt="Screenshot 2023-09-08 at 12 01 35" src="https://github.com/informalsystems/hermes/assets/106849/e8bd333c-e9b4-49a4-98ca-faea3bcebebb">

What does your `[telemetry]` section in the Hermes config look like? Perhaps you need to set `0.0.0.0` for the host, otherwise I am not sure Prometheus can connect to it from the Docker container (though that's never been an issue for me, but I can't think of something else).

```
[telemetry]
enabled = true
host    = '0.0.0.0'
port    = 3001
```

**Comment by taitruong** [comment]
> Ok then yeah Prometheus should point to `host.docker.internal` and Grafana should use the Docker container name. Here in my case it's just `prometheus`:
> 
> <img alt="Screenshot 2023-09-08 at 12 01 35" width="592" src="https://user-images.githubusercontent.com/106849/266575097-e8bd333c-e9b4-49a4-98ca-faea3bcebebb.png">
> What does your `[telemetry]` section in the Hermes config look like? Perhaps you need to set `0.0.0.0` for the host, otherwise I am not sure Prometheus can connect to it from the Docker container (though that's never been an issue for me, but I can't think of something else).
> 
> ```toml
> [telemetry]
> enabled = true
> host    = '0.0.0.0'
> port    = 3001
> ```

Setting host to `0.0.0.0` leads to `address already in use`. But this isn't the problem, `127.0.0.1` in config.toml is correct, also `host.docker.internal:3001` in prometheus.yml is correct. Otherwise I would have got an error when adding prometheus as datasource (tested it).

Interestingly when I try to to explore: I see only these 5 metrics:
![image](https://github.com/informalsystems/hermes/assets/776986/cad6f495-c1f1-4e29-b928-e6d5ce6eed1a)

I also updated using latest Grafana 10.0.5 and plugin - Loki 5.0.0 and Prometheus 5.0.0. Same error here.

**Comment by taitruong** [comment]
Took me forever but found the problem: docker maps to port `0.0.0.0` by default - not `127.0.0.1`. So in Hermes `config.toml`, it needs to change to this: `host = '0.0.0.0'`.

In documentation, Grafana, Lok, Promtail, Prometheus is setup in docker containers - except for Hermes. So `host.docker.internal:3001` in `prometheus.yml` is not working:
```yaml
...
    static_configs:
      - targets: ["host.docker.internal:3001"]
...
```

For a real production setup, Hermes should also be setup in a docker container. Configuration example in docker-compose
I was trying to set explicitly `127.0.0.1` in `docker-compose.yaml`, like this:

```yaml
networks:
  grafana:
    driver: bridge

services:
  hermes-relayer:
    container_name: hermes-relayer
    image: arkprotocol/ics721-relayer-testnet-hermes:v0.0.11
    labels:
      logging: 'promtail'
      logging_jobname: 'containerlogs'
    ports:
      - '3001:3001'
    networks:
      - grafana
...
```

Then in prometheus.yml it can access hermes container, like this:

```yaml
...
    static_configs:
      - targets:
          - hermes-relayer:3001
...
```

Explained here: https://github.com/docker/compose/issues/4799#issuecomment-623504144
