### ISSUE TITLE
`hermes clear packets` relays - but `hermes start` does not

### ISSUE THREAD

**Issue by taitruong** [informalsystems/hermes#3596]
I'm using Hermes v1.6.0, everything seems to be properly configured. When running `hermes start`, the only error shown is this:

> ERROR ThreadId(01) supervisor.init_subscriptions: failed to subscribe to events of uni-6: event source error: failed to create WebSocket driver for chain uni-6 with address wss://juno-testnet-rpc.polkachu.com/websocket

And health-check tells me this:

```sh
2023-09-10T19:25:04.230341Z  INFO ThreadId(01) running Hermes v1.6.0
2023-09-10T19:25:04.230414Z  INFO ThreadId(01) health_check{chain=elgafar-1}: performing health check...
2023-09-10T19:25:05.052797Z  WARN ThreadId(19) health_check{chain=elgafar-1}: Chain 'elgafar-1' has no minimum gas price value configured for denomination 'ustars'. This is usually a sign of misconfiguration, please check your chain and relayer configurations
2023-09-10T19:25:05.449366Z TRACE ThreadId(19) health_check{chain=elgafar-1}: parsed version specification application=starsd version=12.0.0-alpha.1 git_commit=49feb54ca7dfdcfa0afbb615d1d298920be218ab sdk_version=0.45.16 ibc_go_status=Some(Version { major: 4, minor: 4, patch: 2 }) tendermint_version=Some(Version { major: 0, minor: 34, patch: 27 }) comet_version=Some(Version { major: 0, minor: 7, patch: 0 })
2023-09-10T19:25:05.449464Z DEBUG ThreadId(19) health_check{chain=elgafar-1}: running diagnostic on version info Cosmos SDK 0.45.16, IBC-Go 4.4.2, Tendermint 0.34.27, CometBFT 0.7.0
2023-09-10T19:25:06.596551Z  WARN ThreadId(19) health_check{chain=elgafar-1}: Will use fallback value for max_block_time: `30s`. Error: response error: Internal error: genesis response is large, please use the genesis_chunked API instead (code: -32603)
2023-09-10T19:25:06.596835Z  INFO ThreadId(01) health_check{chain=elgafar-1}: chain is healthy
2023-09-10T19:25:06.596908Z  INFO ThreadId(01) health_check{chain=uni-6}: performing health check...
2023-09-10T19:25:07.026593Z  WARN ThreadId(53) health_check{chain=uni-6}: Chain 'uni-6' has no minimum gas price value configured for denomination 'ujunox'. This is usually a sign of misconfiguration, please check your chain and relayer configurations
2023-09-10T19:25:07.153838Z TRACE ThreadId(53) health_check{chain=uni-6}: parsed version specification application=junod version=v17.0.0-alpha.2 git_commit=78b81c55a875dc6c2acc3be3580ea10ff2c7f6dd sdk_version=0.47.4 ibc_go_status=Some(Version { major: 7, minor: 2, patch: 0 }) tendermint_version=None comet_version=Some(Version { major: 0, minor: 37, patch: 2 })
2023-09-10T19:25:07.153928Z DEBUG ThreadId(53) health_check{chain=uni-6}: running diagnostic on version info Cosmos SDK 0.47.4, IBC-Go 7.2.0, Tendermint UNKNOWN, CometBFT 0.37.2
2023-09-10T19:25:07.447504Z  WARN ThreadId(53) health_check{chain=uni-6}: Hermes might be misconfigured for chain 'uni-6'
2023-09-10T19:25:07.447548Z  WARN ThreadId(53) health_check{chain=uni-6}:     Reason: semantic config validation failed for option `max_gas` for chain 'uni-6', reason: `max_gas` = 200000000 is greater than the consensus parameter `max_gas` = 100000000
2023-09-10T19:25:07.447559Z  WARN ThreadId(53) health_check{chain=uni-6}:     Some Hermes features may not work in this mode!
2023-09-10T19:25:07.447625Z  WARN ThreadId(01) health_check{chain=uni-6}: chain is not healthy
2023-09-10T19:25:07.447681Z  INFO ThreadId(01) health_check{chain=pisco-1}: performing health check...
2023-09-10T19:25:07.856424Z  WARN ThreadId(71) health_check{chain=pisco-1}: Chain 'pisco-1' has no minimum gas price value configured for denomination 'uluna'. This is usually a sign of misconfiguration, please check your chain and relayer configurations
2023-09-10T19:25:07.961949Z TRACE ThreadId(71) health_check{chain=pisco-1}: parsed version specification application=terrad version=v2.4.0-rc5 git_commit=ae5e7cd5498186b30da26c388bae741685ea5003 sdk_version=0.46.11 ibc_go_status=Some(Version { major: 6, minor: 1, patch: 1 }) tendermint_version=Some(Version { major: 0, minor: 34, patch: 28 }) comet_version=None
2023-09-10T19:25:07.962038Z DEBUG ThreadId(71) health_check{chain=pisco-1}: running diagnostic on version info Cosmos SDK 0.46.11, IBC-Go 6.1.1, Tendermint 0.34.28, CometBFT UNKNOWN
2023-09-10T19:25:08.220108Z  INFO ThreadId(71) health_check{chain=pisco-1}: Updated `max_block_time` using /genesis endpoint. Old value: `10s`, new value: `30s`
2023-09-10T19:25:08.220237Z  INFO ThreadId(01) health_check{chain=pisco-1}: chain is healthy
SUCCESS performed health check for all chains in the config
```

**Comment by taitruong** [comment]
In `config.toml` I have set `clear_interval = 1`, so it should clear packets after each block.

<details>
<summary>complete `config.toml`:</summary>
<br>
```toml
# The global section has parameters that apply globally to the relayer operation.
[global]

# Specify the verbosity for the relayer logging output. Default: 'info'
# Valid options are 'error', 'warn', 'info', 'debug', 'trace'.
log_level = 'info'

# Specify the mode to be used by the relayer. [Required]
[mode]

# Specify the client mode.
[mode.clients]

# Whether or not to enable the client workers. [Required]
enabled = true

# Whether or not to enable periodic refresh of clients. [Default: true]
# This feature only applies to clients that underlie an open channel.
# For Tendermint clients, the frequency at which Hermes refreshes them is 2/3 of their
# trusting period (e.g., refresh every ~9 days if the trusting period is 14 days).
# Note: Even if this is disabled, clients will be refreshed automatically if
#      there is activity on a connection or channel they are involved with.
refresh = true

# Whether or not to enable misbehaviour detection for clients. [Default: false]
misbehaviour = false

# Specify the connections mode.
[mode.connections]

# Whether or not to enable the connection workers for handshake completion. [Required]
enabled = true

# Specify the channels mode.
[mode.channels]

# Whether or not to enable the channel workers for handshake completion. [Required]
enabled = true

# Specify the packets mode.
[mode.packets]

# Whether or not to enable the packet workers. [Required]
enabled = true

# Parametrize the periodic packet clearing feature.
# Interval (in number of blocks) at which pending packets
# should be periodically cleared. A value of '0' will disable
# periodic packet clearing. [Default: 100]
clear_interval = 1

# Whether or not to clear packets on start. [Default: false]
clear_on_start = true

# Toggle the transaction confirmation mechanism.
# The tx confirmation mechanism periodically queries the `/tx_search` RPC
# endpoint to check that previously-submitted transactions
# (to any chain in this config file) have been successfully delivered.
# If they have not been, and `clear_interval = 0`, then those packets are
# queued up for re-submission.
# If set to `false`, the following telemetry metrics will be disabled:
# `acknowledgment_packets_confirmed`, `receive_packets_confirmed` and `timeout_packets_confirmed`.
# [Default: false]
tx_confirmation = true

# The REST section defines parameters for Hermes' built-in RESTful API.
# https://hermes.informal.systems/rest.html
[rest]

# Whether or not to enable the REST service. Default: false
enabled = true

# Specify the IPv4/6 host over which the built-in HTTP server will serve the RESTful
# API requests. Default: 127.0.0.1
host = '0.0.0.0' # need to set this to `0.0.0.0` to allow external access within docker! check here: https://github.com/informalsystems/hermes/issues/3592#issuecomment-1712645510

# Specify the port over which the built-in HTTP server will serve the restful API
# requests. Default: 3000
port = 3999


# The telemetry section defines parameters for Hermes' built-in telemetry capabilities.
# https://hermes.informal.systems/telemetry.html
[telemetry]

# Whether or not to enable the telemetry service. Default: false
enabled = true

# Specify the IPv4/6 host over which the built-in HTTP server will serve the metrics
# gathered by the telemetry service. Default: 127.0.0.1
host = '0.0.0.0' # need to set this to `0.0.0.0` to allow external access within docker! check here: https://github.com/informalsystems/hermes/issues/3592#issuecomment-1712645510

# Specify the port over which the built-in HTTP server will serve the metrics gathered
# by the telemetry service. Default: 3001
port = 3001


# A chains section includes parameters related to a chain and the full node to which
# the relayer can send transactions and queries.
#[[chains]]

# Specify the chain ID. Required
#id = 'wasmd-1'

# Specify the RPC address and port where the chain RPC server listens on. Required
#rpc_addr = 'http://127.0.0.1:26659'

# Specify the GRPC address and port where the chain GRPC server listens on. Required
#grpc_addr = 'http://127.0.0.1:9090'

# Specify the WebSocket address and port where the chain WebSocket server
# listens on. Required
#websocket_addr = 'ws://127.0.0.1:26659/websocket'

# Specify the maximum amount of time (duration) that the RPC requests should
# take before timing out. Default: 10s (10 seconds)
# Note: Hermes uses this parameter _only_ in `start` mode; for all other CLIs,
# Hermes uses a large preconfigured timeout (on the order of minutes).
#rpc_timeout = '10s'

# Specify the prefix used by the chain. Required
#account_prefix = 'wasm'

# Specify the name of the private key to use for signing transactions. Required
# See the Adding Keys chapter for more information about managing signing keys:
#   https://hermes.informal.systems/commands/keys/index.html#adding-keys
#key_name = 'relayer1'

# Specify the address type which determines:
# 1) address derivation;
# 2) how to retrieve and decode accounts and pubkeys;
# 3) the message signing method.
# The current configuration options are for Cosmos SDK and Ethermint.
#
# Example configuration for chains based on Ethermint library:
#
# address_type = { derivation = 'ethermint', proto_type = { pk_type = '/ethermint.crypto.v1.ethsecp256k1.PubKey' } }
#
# Default: { derivation = 'cosmos' }, i.e. address derivation as in Cosmos SDK.
# Warning: This is an advanced feature! Modify with caution.
#address_type = { derivation = 'cosmos' }

# Specify the store prefix used by the on-chain IBC modules. Required
# Recommended value for Cosmos SDK: 'ibc'
#store_prefix = 'ibc'

# Specify the default amount of gas to be used in case the tx simulation fails,
# and Hermes cannot estimate the amount of gas needed.
# Default: 100 000
#default_gas = 0

# Specify the maximum amount of gas to be used as the gas limit for a transaction.
# If `default_gas` is unspecified, then `max_gas` will be used as `default_gas`.
# Default: 400 000
#max_gas = 40000000

# Specify the price per gas used of the fee to submit a transaction and
# the denomination of the fee. Required
#gas_price = { price = 0.1, denom = 'ucosm' }

# Multiply this amount with the gas estimate, used to compute the fee
# and account for potential estimation error.
#
# Example: With this setting set to 1.1, then if the estimated gas
# is 80_000, then gas used to compute the fee will be adjusted to
# 80_000 * 1.1 = 88_000.
#
# Default: 1.1, ie. the gas is increased by 10%
# Minimum value: 1.0
#gas_multiplier = 1.1

# Specify how many IBC messahostges at most to include in a single transaction.
# Default: 30
#max_msg_num = 30

# Specify the maximum size, in bytes, of each transaction that Hermes will submit.
# Default: 2097152 (2 MiB)
#max_tx_size = 2097152

# Specify the maximum amount of time to tolerate a clock drift.
# The clock drift parameter defines how much new (untrusted) header's time
# can drift into the future. Default: 5s
#clock_drift = '5s'

# Specify the maximum time per block for this chain.
# The block time together with the clock drift are added to the source drift to estimate
# the maximum clock drift when creating a client on this chain. Default: 30s
# For cosmos-SDK chains a good approximation is `timeout_propose` + `timeout_commit`
# Note: This MUST be the same as the `max_expected_time_per_block` genesis parameter for Tendermint chains.
#max_block_time = '30s'

# Specify the amount of time to be used as the light client trusting period.
# It should be significantly less than the unbonding period
# (e.g. unbonding period = 3 weeks, trusting period = 2 weeks).
# Default: 2/3 of the `unbonding period` for Cosmos SDK chains
#trusting_period = '14days'

# Specify the trust threshold for the light client, ie. the maximum fraction of validators
# which have changed between two blocks.
# Default: { numerator = '1', denominator = '3' }, ie. 1/3.
# Warning: This is an advanced feature! Modify with caution.
#trust_threshold = { numerator = '1', denominator = '3' }

# Specify a string that Hermes will use as a memo for each transaction it submits
# to this chain. The string is limited to 50 characters. Default: '' (empty).
# Note: Hermes will append to the string defined here additional
# operational debugging information, e.g., relayer build version.
#memo_prefix = ''

# This section specifies the filters for policy based relaying.
#
# Default: no policy / filters, allow all packets on all channels.
#
# Only packet filtering based on channel identifier can be specified.
# A channel filter has two fields:
# 1. `policy` - one of two types are supported:
#       - 'allow': permit relaying _only on_ the port/channel id in the list below,
#       - 'deny': permit relaying on any channel _except for_ the list below.
# 2. `list` - the list of channels specified by the port and channel identifiers.
#             Optionally, each element may also contains wildcards, for eg. 'ica*'
#             to match all identifiers starting with 'ica' or '*' to match all identifiers.
#
# Example configuration of a channel filter, only allowing packet relaying on
# channel with port ID 'transfer' and channel ID 'channel-0', as well as on
# all ICA channels.
#
# [chains.packet_filter]
# policy = 'allow'
# list = [
#   ['ica*', '*'],
#   ['transfer', 'channel-0'],
# ]

# Specify that the transaction fees should be payed from this fee granter's account.
# Optional. If unspecified (the default behavior), then no fee granter is used, and
# the account specified in `key_name` will pay the tx fees for all transactions
# submitted to this chain.
# fee_granter = ''

[[chains]]
id = 'elgafar-1'
rpc_addr = 'https://rpc.elgafar-1.stargaze-apis.com:443'
grpc_addr = 'http://grpc-1.elgafar-1.stargaze-apis.com:26660/'
event_source = { mode = 'push', url = 'wss://rpc.elgafar-1.stargaze-apis.com:443/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
account_prefix = 'stars'
key_name = 'stargaze_ark_relayer'
store_prefix = 'ibc'
default_gas = 40000
max_gas = 600000
gas_price = { price = 0.04, denom = 'ustars' }
gas_multiplier = 1.3
max_msg_num = 10
max_tx_size = 4194304 # 4MiB
clock_drift = '300s'
max_block_time = '30s'
trusting_period = '1209599s' # 14 days (unbonding period) minus 1 sec
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = 'allow'
list = [
  # Stargaze ICS721 channels
  # IMPORTANT: do NOT change comments for each channel below! `create-channels.sh` does a search and replace!
  ## ICS721 with rate limiter outgoing proxy (managed by Ark)
  ['wasm.stars165fr5j3ea0dk5yr5sr4h8uw76z5fd34lpnqc2x80ya9xkx9u0k3qjrqpzq', 'channel-553'], # CHANNEL_1_STARGAZE_TO_JUNO, channel-651
]

[[chains]]
id = 'uni-6'
rpc_addr = 'https://juno-testnet-rpc.polkachu.com:443'
grpc_addr = 'http://juno-testnet-grpc.polkachu.com:12690'
event_source = { mode = 'push', url = 'wss://juno-testnet-rpc.polkachu.com:443/websocket', batch_delay = '500ms' }
# BACKUP:
# rpc_addr = 'https://uni-rpc.reece.sh:443'
# grpc_addr = 'http://5.161.80.115:9090'
# websocket_addr = 'wss://uni-rpc.reece.sh:443/websocket'
rpc_timeout = '10s'
account_prefix = 'juno'
key_name = 'juno_ark_relayer'
store_prefix = 'ibc'
default_gas = 4500
max_gas = 800000
gas_price = { price = 0.0045, denom = 'ujunox' }
gas_multiplier = 1.5
max_msg_num = 10
max_tx_size = 4194304 # 4MiB
clock_drift = '300s'
max_block_time = '30s'
trusting_period = '2419199s' # 28 days (unbonding period) minus 1 sec
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = 'allow'
list = [
  # Juno ICS721 channels
  # IMPORTANT: do NOT change comments for each channel below! `create-channels.sh` does a search and replace!
  ## ICS721 with rate limiter outgoing proxy (managed by Ark)
  ['wasm.juno1uvflayc34fs9r3tzcausztks2058ecpt5kqtzf3sz5kwnu7fjtfqn7zmtj', 'channel-651'], # CHANNEL_1_JUNO_TO_STARGAZE, channel-553
]
```
</details>
