### ISSUE TITLE
`config auto` cannot generate chain config without valid WebSocket endpoint

### ISSUE THREAD

**Issue by cifer-ai** [informalsystems/hermes#3913]
## Summary of Bug

We auto generate hermes config using this command:
$ hermes config auto --output $HOME/.hermes/config.toml --chain cifer --chain

Then we get this output:
However, configurations for the following chains were not able to be generated: cifer

## Version

hermes version 1.8.2, ibc-rs version 1.0.0

## Steps to Reproduce

We suspect may we miss some parameters in our Chain config such slip44 and key_algo as you can see in this repo:
https://github.com/cosmos/chain-registry/tree/master/cifer

## Acceptance Criteria

In this case, please kindly check if we miss any parameters in our config file that cause Hermes unable to generate Cifer chain config in config.toml

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
I looked into it and the issue was that `config auto` failed to find a valid WebSocket endpoint.

I have [changed the logic](https://github.com/informalsystems/hermes/pull/3920) so that it nows uses the `pull` event source by default, which does not rely on WebSocket.

<details>
<summary>Here is the config file it generates now</summary>


```toml
[global]
log_level = "info"

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false
auto_register_counterparty_payee = false

[mode.packets.ics20_max_memo_size]
enabled = true
size = 32768

[mode.packets.ics20_max_receiver_size]
enabled = true
size = 2048

[rest]
enabled = false
host = "127.0.0.1"
port = 3000

[telemetry]
enabled = false
host = "127.0.0.1"
port = 3001

[telemetry.buckets.latency_submitted]
start = 500
end = 20000
buckets = 10

[telemetry.buckets.latency_confirmed]
start = 1000
end = 30000
buckets = 10

[[chains]]
type = "CosmosSdk"
id = "cifer"
rpc_addr = "https://cif_node.cifer.ai/"
grpc_addr = "http://grpc.cifer.ai/"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "cife"
key_name = ""
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 400000
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
query_packets_chunk_size = 50
clock_drift = "5s"
max_block_time = "30s"
client_refresh_rate = "1/3"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false

[chains.event_source]
mode = "pull"
interval = "500ms"
max_retries = 4

[chains.trust_threshold]
numerator = 2
denominator = 3

[chains.gas_price]
price = 5.0
denom = "ucif"

[chains.packet_filter]
policy = "allowall"

[chains.packet_filter.min_fees]

[chains.dynamic_gas_price]
enabled = false
multiplier = 1.1
max = 0.6

[chains.address_type]
derivation = "cosmos"

[chains.excluded_sequences]

[tracing_server]
enabled = false
port = 5555
```

</details>
