### ISSUE TITLE
Undefined behaviour with compat_mode 0.37

### ISSUE THREAD

**Issue by faust403** [informalsystems/hermes#4178]
## Summary of Bug

For some reason hermes doesn't work properly with compat_mode 0.37

## Version

hermes version: 1.10.3+e26d356a

## Steps to Reproduce

Open you hermes config file and put this piece of config into it:
```toml
[[chains]]
id = 'pion-1'
rpc_addr = 'https://rpc-lunara.pion-1.ntrn.tech/'
grpc_addr = 'http://grpc-lunara.pion-1.ntrn.tech:80'
event_source = { mode = 'pull', url = 'wss://rpc-lunara.pion-1.ntrn.tech/websocket', batch_delay = '1s', max_retries = 4 }
rpc_timeout = '40s'
account_prefix = 'neutron'
key_name = 'main'
store_prefix = 'ibc'
default_gas = 5000000
max_gas = 50000000
gas_price = { price = 0.02, denom = 'untrn' }
gas_multiplier = 1.6
dynamic_gas_price = { enabled = true, multiplier = 1.2, max = 0.06 }
max_msg_num = 20
max_tx_size = 2097152
clock_drift = '20s'
max_block_time = '75s'
trusting_period = '5days'
ccv_consumer_chain = true
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
memo_prefix = 'Relayed by Neutron'

[[chains]]
id = 'mocha-4'
rpc_addr = "https://rpc-mocha-full.avril14th.org"
grpc_addr = "https://celestia-testnet-grpc.publicnode.com:443"
event_source = { mode = 'push', url = 'ws://rpc-mocha.pops.one:26657/websocket', batch_delay = '500ms' }
compat_mode = '0.37'
rpc_timeout = '40s'
account_prefix = 'celestia'
key_name = 'main'
store_prefix = 'ibc'
default_gas = 5000000
max_gas = 50000000
gas_price = { price = 0.01, denom = 'utia' }
gas_multiplier = 1.6
dynamic_gas_price = { enabled = true, multiplier = 1.2, max = 0.06 }
max_msg_num = 20
max_tx_size = 2097152
clock_drift = '20s'
max_block_time = '75s'
trusting_period = '5days'
ccv_consumer_chain = false
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
memo_prefix = 'Relayed by Neutron'
```
Right after that try to build a new IBC client on mocha-4 with ref on pion-1
`hermes create client --host-chain mocha-4 --reference-chain pion-1`

You'll get a `07-tendermint-0` client id which is absurd
![image](https://github.com/user-attachments/assets/27652961-4c9e-41a8-bee2-f0a0dd73e16d)

Nevertheless, try to find this transaction on mintscan and copy the real client id (in reality it's the correct one), try to build a connection between 2 IBC clients (in my case it's pion-1 <-> mocha-4). Btw, client builds successfully when doing it on pion-1 with ref on mocha-4

Type
`hermes create connection --a-chain pion-1 --a-client 07-tendermint-377 --b-client 07-tendermint-493`
![image](https://github.com/user-attachments/assets/c32e9fe2-291c-452c-8942-27fe7629137a)

As you can see it infinitely tries to open a connection with client 07-tendermint-0

## Acceptance Criteria

In the new version of hermes I believe it should be compatible with compat_mode 0.37 because if change this parameter to 0.34 it works fine
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
